### ISSUE TITLE
Distance Sensor on Claw

### ISSUE THREAD

**Issue by josephhadad05** [Creekside-Robotics/2023-Offseason#4]
## Distance Sensor on Claw 
One of the many subsystems on our robot right now is the Claw. Currently the Claw is a simple mechanism that operates with a single actuator. If you look in `Claw.java`, you will see that the code reflects this. 

Your job is to add code to support an analog ultrasonic on the claw. This sensor will allow the claw to automatically grab objects that enter it, taking strain off the driver. 

### Tasks
- [x] Add the sensor object to the `Claw.java` subsystem.
- [x] Add the appropriate methods to the `Claw.java` subsystem, this should include a method to get the distance from the sensor, and a method that return whether or not an object is in the claw.
- [x] Add a command in the appropriate folder that leaves the claw open until an object enters it. Once the object enters the claw, that claw should close before ending the command.

### Tips
- Data coming from any sensor will have some sort of fluctuation, make sure you are smoothing/filtering the data.
- Try to match the current level of formatting, comments, and documentation in the project.
- If you don't understand what you are coding, stop coding. Although copying code can be convenient at times, this assignment is about learning so make sure you understand all the code you submit.
- Feel free to reach out for help if you need it.

### Resources
- [Here](https://docs.wpilib.org/en/stable/docs/software/advanced-controls/filters/introduction.html) is a link to a page that explains how to implement filters in code.
- We will be using an analog ultrasonic sensor on our robot to estimate distance. [Here](https://www.revrobotics.com/rev-31-1505/) is a link explaining how to program one.
- [Command-Based Programming](https://docs.wpilib.org/en/stable/docs/software/commandbased/what-is-command-based.html) is the framework that is used in this project. This link is in the readme, but I am attaching it here as well.

Good Luck!
