### ISSUE TITLE
USB Camera

### ISSUE THREAD

**Issue by josephhadad05** [Creekside-Robotics/2023-Offseason#8]
## USB Camera
The goal of this issue is to write code to stream data from a camera to the driver's computer.  This camera stream should be used by the driver when intaking game pieces from the ground.

### Tasks
- [x] Create Camera Object
- [x] Stream Camera to DriverStation Application
- [x] Change the drive style to robot oriented when the camera stream will be used (intake objects, etc.)
